import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from winqstep.quickstep import (
    QuickStepInputError,
    quickstep_input_from_dict,
    render_quickstep_input,
)


ROOT = Path(__file__).resolve().parents[1]


class QuickStepTests(unittest.TestCase):
    def test_renders_energy_snapshot(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_energy.json").read_text(encoding="utf-8"))
        expected = (ROOT / "tests" / "fixtures" / "quickstep_energy.inp").read_text(encoding="utf-8")

        self.assertEqual(render_quickstep_input(quickstep_input_from_dict(data)), expected)

    def test_renders_geo_opt_snapshot(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_geo_opt.json").read_text(encoding="utf-8"))
        expected = (ROOT / "tests" / "fixtures" / "quickstep_geo_opt.inp").read_text(encoding="utf-8")

        self.assertEqual(render_quickstep_input(quickstep_input_from_dict(data)), expected)

    def test_renders_energy_force_snapshot(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_energy_force.json").read_text(encoding="utf-8"))
        expected = (ROOT / "tests" / "fixtures" / "quickstep_energy_force.inp").read_text(encoding="utf-8")

        self.assertEqual(render_quickstep_input(quickstep_input_from_dict(data)), expected)

    def test_renders_energy_force_without_geo_opt_section(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_energy_force.json").read_text(encoding="utf-8"))
        rendered = render_quickstep_input(quickstep_input_from_dict(data))
        self.assertIn("  RUN_TYPE ENERGY_FORCE\n", rendered)
        self.assertIn("    &FORCES ON\n", rendered)
        self.assertIn("    &POISSON\n      PERIODIC XYZ\n    &END POISSON\n", rendered)
        self.assertNotIn("&GEO_OPT", rendered)
        self.assertNotIn("&MOTION", rendered)

    def test_rejects_non_quickstep_run_type(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_energy.json").read_text(encoding="utf-8"))
        data["run_type"] = "MD"

        with self.assertRaises(QuickStepInputError):
            quickstep_input_from_dict(data)

    def test_rejects_missing_kind(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_energy.json").read_text(encoding="utf-8"))
        data["structure"]["kinds"] = data["structure"]["kinds"][:1]

        with self.assertRaises(QuickStepInputError):
            quickstep_input_from_dict(data)

    def test_rejects_zero_vector_for_periodic_cell(self) -> None:
        data = json.loads((ROOT / "examples" / "quickstep_energy.json").read_text(encoding="utf-8"))
        data["structure"]["cell"]["a"] = [0.0, 0.0, 0.0]

        with self.assertRaisesRegex(QuickStepInputError, "periodic cell vectors"):
            quickstep_input_from_dict(data)

    def test_cli_writes_output_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            output_path = Path(tmp_dir) / "water.inp"
            completed = subprocess.run(
                [
                    sys.executable,
                    str(ROOT / "scripts" / "render_quickstep_input.py"),
                    "--input-json",
                    str(ROOT / "examples" / "quickstep_energy.json"),
                    "--output",
                    str(output_path),
                ],
                capture_output=True,
                check=False,
            )

            self.assertEqual(completed.returncode, 0, completed.stderr.decode("utf-8", errors="replace"))
            self.assertTrue(output_path.read_text(encoding="utf-8").startswith("# Generated by WinQStep"))


if __name__ == "__main__":
    unittest.main()
